# MEDIA QUERIES
small                : 'only screen'
small-down           : 'screen and (width <= 40em)'
small-only           : 'screen and (width <= 40em)'

medium               : 'screen and (width >= 40.063em)'
medium-down          : 'screen and (width <= 64em)'
medium-only          : 'screen and (width >= 40.063em) and (width <= 64em)'

large                : 'screen and (width >= 60.063em)'
large-down           : 'screen and (width <= 90em)'
large-only           : 'screen and (width >= 60.063em) and (width <= 90em)'

xlarge               : 'screen and (width >= 90.063em)'
xlarge-down          : 'screen and (width <= 120em)'
xlarge-only          : 'screen and (width >= 90.063em) and (width <= 120em)'

xxlarge              : 'screen and (width >= 120.063em)'
xxlarge-down         : 'screen and (width <= 9999999em)'
xxlarge-only         : 'screen and (width >= 120.063em) and (width <= 9999999em)'



# COLORS
primary-color        : '#197bee'
secondary-color      : '#197bee'

type-primary-color   : '#555'
type-secondary-color : '#b3b3b3'
type-oposit-color    : '#fff'
divider-color        : '#e7e7e7'

table-row-even-color : '#f6f6f6'
table-row-odd-color  : '#fff'

body-primary-color   : '#fff'
body-secondary-color : '#e0e0e0'

error-color          : '#ff4f37'
warning-color        : '#ffdd22'
success-color        : '#7dc142'
help-color           : '#b2ebf2'



# TYPE DEFAULTS
font-family          : '"Raleway", arial, sans-serif'
font-size            : '14px'
font-weight          : 'normal'
line-height          : '1.5'
margin               : '0 0 20px'
radius               : '5px'